services:
  api:
    build: .
    env_file: .env.local
    ports:
      - "80:80"

  db:
    image: postgres
    ports:
     - 25432:5432
    restart: always
    volumes:
      - ./data/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./data/${DB_INIT_FILE}:/docker-entrypoint-initdb.d/${DB_INIT_FILE}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_INIT_FILE=${DB_INIT_FILE}
