services:
  api:
    build: .
    env_file: .env.local
    ports:
      - "80:80"

  db:
    image: postgres
    ports:
     - 25432:5432
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
