services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    env_file: ../.env.local
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - "80:80"
    volumes:
      - ..:/app

  db:
    image: postgres
    ports:
     - 5432:5432
    restart: always
    volumes:
      - ../data:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
